### ISSUE TITLE
Missing method "init_distributed_mode()" in utils/distributed.py

### ISSUE THREAD

**Issue by KlrShaK** [yifeisu/avdn-challenge#3]
In the folder `\TG-GAT\src\3_et_imga_mhca_ground_gat_robert_yolov5x_ngpus` , The main.py file line number 224 uses the method `rank = init_distributed_mode(args)` . However this method is not defined in utils/distributed.py . I was able to overcome the error by uncommenting the commented lines and changing it to init_distributed() . Like so - 

>     if args.world_size > 1:
>        rank = init_distributed(args)
>        torch.cuda.set_device(args.local_rank)
>        torch.distributed.barrier()

However I feel like it is not the intended use case and it is unreliable during training as it sometimes fails to start training.

I request you to please provide the code for the custom function init_distributed_mode() that you created for reproducibility.

**Comment by yifeisu** [comment]
I do have the 'init_distributed_mode' function in the 'utils' I implemented. However, I forgot to check it when merging your code, which is the reason for the conflict. The 'utils' in the original AVDN baseline repository is not what this code repository requires.
